Entity/Shops.php
<?php

namespace CMS\CatalogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Shops
 */
class Shops
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $address;

    /**
     * @var string
     */
    private $addressRegistration;

    /**
     * @var string
     */
    private $email;

    /**
     * @var string
     */
    private $phone;

    /**
     * @var \DateTime
     */
    private $date_create;

    /**
     * @var \DateTime
     */
    private $date_update;

    /**
     * @var integer
     */
    private $create_by;

    /**
     * @var integer
     */
    private $update_by;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Shops
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set address
     *
     * @param string $address
     * @return Shops
     */
    public function setAddress($address)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Get address
     *
     * @return string 
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Set addressRegistration
     *
     * @param string $addressRegistration
     * @return Shops
     */
    public function setAddressRegistration($addressRegistration)
    {
        $this->addressRegistration = $addressRegistration;

        return $this;
    }

    /**
     * Get addressRegistration
     *
     * @return string 
     */
    public function getAddressRegistration()
    {
        return $this->addressRegistration;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Shops
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set phone
     *
     * @param string $phone
     * @return Shops
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * Get phone
     *
     * @return string 
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Set date_create
     *
     * @param \DateTime $date_create
     * @return Shops
     */
    public function setDateCreate($date_create)
    {
        $this->date_create = new \DateTime();

        return $this;
    }

    /**
     * Get date_create
     *
     * @return \DateTime 
     */
    public function getDateCreate()
    {
        return $this->date_create;
    }

    /**
     * Set date_update
     *
     * @param \DateTime $date_update
     * @return Shops
     */
    public function setDateUpdate($date_update)
    {
        $this->date_update = new \DateTime();

        return $this;
    }

    /**
     * Get date_update
     *
     * @return \DateTime 
     */
    public function getDateUpdate()
    {
        return $this->date_update;
    }

    /**
     * Set create_by
     *
     * @param integer $create_by
     * @return Shops
     */
    public function setCreateBy($create_by)
    {
        $this->create_by = $create_by;

        return $this;
    }

    /**
     * Get create_by
     *
     * @return integer 
     */
    public function getCreateBy()
    {
        return $this->create_by;
    }

    /**
     * Set update_by
     *
     * @param integer $update_by
     * @return Shops
     */
    public function setUpdateBy($update_by)
    {
        $this->update_by = $update_by;

        return $this;
    }

    /**
     * Get update_by
     *
     * @return integer 
     */
    public function getUpdateBy()
    {
        return $this->update_by;
    }
}

Form/PaymentTypesType.php
<?php

namespace CMS\CatalogBundle\Form;

use CMS\CatalogBundle\Form\Types\PaymentServiceType;
use CMS\LocalizationBundle\Form\Types\LocaleTextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PaymentTypesType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', LocaleTextType::class)
            ->add('paymentService', PaymentServiceType::class)
            ->add('is_deleted')
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'CMS\CatalogBundle\Entity\PaymentTypes'
        ));
    }
}

Controller/PaymentTypesController.php
<?php
/**
 * Created by PhpStorm.
 * User: work-pc
 * Date: 25.09.16
 * Time: 15:55
 */

namespace CMS\CatalogBundle\Controller;


use CMS\CatalogBundle\Entity\PaymentTypes;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class PaymentTypesController extends Controller
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function listAction(){
        return $this->render('CatalogBundle:PaymentTypes:list.html.twig', array(
            'payment_types' => $this->get('cms.catalog.payment_types.service')->findAll()
        ));
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function createAction(Request $request){
        $service = $this->get('cms.catalog.payment_types.service');

        $form = $service->generateForm();

        if ($request->isMethod('POST')){
            $form->handleRequest($request);

            if ($form->isValid()){
                /** @var PaymentTypes $data */
                $data = $form->getData();

                $data->setDateUpdate(new \DateTime());
                $data->setDateCreate(new \DateTime());
                $data->setCreateBy($this->getUser()->getId());
                $data->setUpdateBy($this->getUser()->getId());

                $service->create($data);

                return $this->redirect($this->generateUrl('cms_catalog_payment_types_list'));
            }
        }

        return $this->render('CatalogBundle:PaymentTypes:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function editAction(Request $request, $id){
        $service = $this->get('cms.catalog.payment_types.service');

        $form = $service->generateForm($service->findOneBy(['id' => $id]));

        if ($request->isMethod('POST')){
            $form->handleRequest($request);

            if ($form->isValid()){
                /** @var PaymentTypes $data */
                $data = $form->getData();

                $data->setDateUpdate(new \DateTime());
                $data->setCreateBy($this->getUser()->getId());

                $service->update($data);

                return $this->redirect($this->generateUrl('cms_catalog_payment_types_list'));
            }
        }

        return $this->render('CatalogBundle:PaymentTypes:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction($id){
        $service = $this->get('cms.catalog.payment_types.service');

        $service->delete($id);

        return $this->redirect($this->generateUrl('cms_catalog_payment_types_list'));
    }
}

Resources/views/PaymentTypes/edit.html.twig
{% extends 'DashboardBundle:Layout:base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts '@file_uploader_js' '@localization_tabs_js' %}
    <script type="text/javascript" src="{{ asset_url }}" xmlns="http://www.w3.org/1999/html"></script>
    {% endjavascripts %}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {% stylesheets
    '@fileupload_css' %}
    <link rel="stylesheet" href="{{ asset_url }}"/>
    {% endstylesheets %}
{% endblock %}

{% block body %}
    {% embed "CatalogBundle::main.html.twig" %}
        {% block main %}
            {% form_theme form 'CatalogBundle::fields.html.twig' %}
            <div class='row'>
                <div class='col-md-12'>
                    {{ show_locale_tabs() }}
                    </br>
                    <form method="post">
                        {{ form_errors(form) }}

                        {{ form_row(form.title,{
                                'label': 'Title'|trans({},'messages'),
                            })
                        }}
                        {{ form_row(form.paymentService,{
                                'label': 'Payment service'|trans({},'messages'),
                            })
                        }}

                        {{ form_rest(form) }}

                        <div class="well well-sm text-right">
                            <input type="submit" class="btn btn-sm btn-primary" value="{{'Save'|trans}}"/>
                            <a class="btn btn-sm btn-default" href="javascript:history.go(-1)">{{'Cancel'|trans}}</a>
                        </div>
                    </form>
                </div>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}

Resources/views/PaymentTypes/list.html.twig
{% extends 'DashboardBundle:Layout:base.html.twig' %}

{% block body %}
    {% embed "CatalogBundle::main.html.twig" %}
        {% block panelButtons %}
            <a href="{{ url('cms_catalog_payment_types_create') }}"
               class="btn btn-success btn-xs">
                <i class="glyphicon glyphicon-plus"></i>
                {{ 'Add'|trans }}
            </a>
        {% endblock %}

        {% block main %}
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <th><input type="checkbox" data-action="selectAll"/></th>
                    <th>ID</th>
                    <th>{{'Title'|trans}}</th>
                    <th>{{'Payment type service'|trans}}</th>
                    <th>{{'Date update'|trans}}</th>
                    <th>{{'Update by'|trans}}</th>
                    <th></th>
                    <th></th>
                    </thead>
                    <tbody>
                    {% for payment_type in payment_types %}
                        <tr>
                            <td><input type="checkbox" value="{{payment_type.id}}" name="mark[]"/></td>
                            <td>{{payment_type.id}}</td>
                            <td>
                                <a href="{{url('cms_catalog_payment_types_edit', {'id': payment_type.id})}}">
                                    {{ payment_type.title|locale }}
                                </a>
                            </td>
                            <td>{{ payment_type.paymentService }}</td>
                            <td>{{ payment_type.dateCreate|date('d.m.Y')}}</td>
                            <td>{{ payment_type.createBy }}</td>
                            <td><a href='{{url('cms_catalog_payment_types_edit', {'id': payment_type.id})}}'><span class="glyphicon lead text-primary glyphicon-pencil"></span></a></td>
                            <td><a href='{{url('cms_catalog_payment_types_delete', {'id': payment_type.id})}}'><span class="glyphicon lead text-danger glyphicon-remove-circle"></span></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}